from typing import List, Tuple

CALL_INPUTS: List[Tuple[str, dict]] = [
    (
        "Hull_call_classic",
        {
            "S_t": 42.0,
            "K": 40.0,
            "T": 0.5,
            "r": 0.10,
            "sigma": 0.20,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "ATM_call_baseline",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.05,
            "sigma": 0.20,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Dividend_ATM_call",
        {
            "S_t": 50.0,
            "K": 50.0,
            "T": 0.5,
            "r": 0.06,
            "sigma": 0.30,
            "q": 0.03,
            "option_type": "call",
        },
    ),
    (
        "Deep_ITM_call_long_T",
        {
            "S_t": 150.0,
            "K": 100.0,
            "T": 2.0,
            "r": 0.02,
            "sigma": 0.25,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Short_maturity_call_OTM",
        {
            "S_t": 100.0,
            "K": 105.0,
            "T": 1.0 / 12.0,
            "r": 0.01,
            "sigma": 0.15,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "High_vol_call_with_q",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.03,
            "sigma": 0.35,
            "q": 0.05,
            "option_type": "call",
        },
    ),
    (
        "Low_rate_call",
        {
            "S_t": 120.0,
            "K": 110.0,
            "T": 0.75,
            "r": 0.005,
            "sigma": 0.18,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Neg_rate_call",
        {
            "S_t": 100.0,
            "K": 90.0,
            "T": 1.5,
            "r": -0.01,
            "sigma": 0.22,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Near_expiry_call_ATM",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0 / 365.0,
            "r": 0.01,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Near_expiry_call_ITM",
        {
            "S_t": 105.0,
            "K": 100.0,
            "T": 1.0 / 365.0,
            "r": 0.01,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Near_expiry_call_OTM",
        {
            "S_t": 95.0,
            "K": 100.0,
            "T": 1.0 / 365.0,
            "r": 0.01,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Very_high_vol_call",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.02,
            "sigma": 1.0,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Deep_OTM_long_call",
        {
            "S_t": 50.0,
            "K": 150.0,
            "T": 3.0,
            "r": 0.02,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "High_dividend_call",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 0.75,
            "r": 0.03,
            "sigma": 0.25,
            "q": 0.10,
            "option_type": "call",
        },
    ),
    (
        "Zero_rates_call",
        {
            "S_t": 100.0,
            "K": 90.0,
            "T": 0.5,
            "r": 0.0,
            "sigma": 0.20,
            "q": 0.0,
            "option_type": "call",
        },
    ),
    (
        "Low_vol_ATM_call",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.03,
            "sigma": 0.05,
            "q": 0.0,
            "option_type": "call",
        },
    ),
]

PUT_INPUTS: List[Tuple[str, dict]] = [
    (
        "ATM_put_baseline",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.05,
            "sigma": 0.20,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "McDonald_like_put",
        {
            "S_t": 40.0,
            "K": 45.0,
            "T": 0.25,
            "r": 0.05,
            "sigma": 0.25,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Dividend_ATM_put",
        {
            "S_t": 50.0,
            "K": 50.0,
            "T": 0.5,
            "r": 0.06,
            "sigma": 0.30,
            "q": 0.03,
            "option_type": "put",
        },
    ),
    (
        "Deep_ITM_put_long_T",
        {
            "S_t": 80.0,
            "K": 100.0,
            "T": 2.0,
            "r": 0.01,
            "sigma": 0.25,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Short_maturity_put_ITM",
        {
            "S_t": 100.0,
            "K": 105.0,
            "T": 1.0 / 12.0,
            "r": 0.01,
            "sigma": 0.15,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "OTM_put",
        {
            "S_t": 120.0,
            "K": 100.0,
            "T": 0.5,
            "r": 0.02,
            "sigma": 0.20,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "High_dividend_put",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.03,
            "sigma": 0.25,
            "q": 0.06,
            "option_type": "put",
        },
    ),
    (
        "Neg_rate_put",
        {
            "S_t": 100.0,
            "K": 110.0,
            "T": 1.5,
            "r": -0.01,
            "sigma": 0.22,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Near_expiry_put_ATM",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0 / 365.0,
            "r": 0.01,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Near_expiry_put_ITM",
        {
            "S_t": 95.0,
            "K": 100.0,
            "T": 1.0 / 365.0,
            "r": 0.01,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Near_expiry_put_OTM",
        {
            "S_t": 105.0,
            "K": 100.0,
            "T": 1.0 / 365.0,
            "r": 0.01,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Very_high_vol_put",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.02,
            "sigma": 1.0,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Deep_OTM_put_long",
        {
            "S_t": 150.0,
            "K": 50.0,
            "T": 3.0,
            "r": 0.02,
            "sigma": 0.30,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "High_dividend_put_shortT",
        {
            "S_t": 100.0,
            "K": 90.0,
            "T": 0.75,
            "r": 0.03,
            "sigma": 0.25,
            "q": 0.08,
            "option_type": "put",
        },
    ),
    (
        "Zero_rates_put",
        {
            "S_t": 90.0,
            "K": 100.0,
            "T": 0.5,
            "r": 0.0,
            "sigma": 0.20,
            "q": 0.0,
            "option_type": "put",
        },
    ),
    (
        "Low_vol_ATM_put",
        {
            "S_t": 100.0,
            "K": 100.0,
            "T": 1.0,
            "r": 0.03,
            "sigma": 0.05,
            "q": 0.0,
            "option_type": "put",
        },
    ),
]
