from typing import List, Tuple

EUROPEAN_CALL_INPUTS: List[Tuple[str, dict]] = [
    (
        "Hull_classic_european_call",
        {
            "sigma": 0.20,
            "T": 0.25,
            "N": 100,
            "S_t": 42.0,
            "r": 0.10,
            "K": 40.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "ATM_european_call",
        {
            "sigma": 0.20,
            "T": 1.0,
            "N": 200,
            "S_t": 100.0,
            "r": 0.05,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Dividend_european_call",
        {
            "sigma": 0.30,
            "T": 0.5,
            "N": 150,
            "S_t": 50.0,
            "r": 0.06,
            "K": 50.0,
            "q": 0.03,
            "r_f": None,
            "asset_type": "dividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Currency_european_call",
        {
            "sigma": 0.15,
            "T": 1.0,
            "N": 200,
            "S_t": 1.25,  # EUR/USD
            "r": 0.02,  # USD rate
            "K": 1.20,
            "q": None,
            "r_f": 0.01,  # EUR rate
            "asset_type": "currency",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Future_european_call",
        {
            "sigma": 0.25,
            "T": 0.75,
            "N": 100,
            "S_t": 2500.0,  # Future price
            "r": 0.03,
            "K": 2400.0,
            "q": None,
            "r_f": None,
            "asset_type": "future",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "High_vol_european_call",
        {
            "sigma": 0.80,
            "T": 1.0,
            "N": 250,
            "S_t": 100.0,
            "r": 0.05,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Short_term_european_call",
        {
            "sigma": 0.20,
            "T": 1.0 / 52.0,  # 1 week
            "N": 50,
            "S_t": 100.0,
            "r": 0.01,
            "K": 102.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Deep_ITM_european_call",
        {
            "sigma": 0.25,
            "T": 2.0,
            "N": 300,
            "S_t": 150.0,
            "r": 0.04,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Low_vol_dividend_european_call",
        {
            "sigma": 0.10,
            "T": 1.0,
            "N": 200,
            "S_t": 100.0,
            "r": 0.03,
            "K": 95.0,
            "q": 0.02,
            "r_f": None,
            "asset_type": "dividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Negative_rate_european_call",
        {
            "sigma": 0.20,
            "T": 1.0,
            "N": 150,
            "S_t": 100.0,
            "r": -0.005,
            "K": 95.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
]

EUROPEAN_PUT_INPUTS: List[Tuple[str, dict]] = [
    (
        "McDonald_european_put",
        {
            "sigma": 0.25,
            "T": 0.25,
            "N": 100,
            "S_t": 40.0,
            "r": 0.05,
            "K": 45.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "ATM_european_put",
        {
            "sigma": 0.20,
            "T": 1.0,
            "N": 200,
            "S_t": 100.0,
            "r": 0.05,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "Dividend_european_put",
        {
            "sigma": 0.30,
            "T": 0.5,
            "N": 150,
            "S_t": 50.0,
            "r": 0.06,
            "K": 50.0,
            "q": 0.03,
            "r_f": None,
            "asset_type": "dividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "Currency_european_put",
        {
            "sigma": 0.12,
            "T": 0.5,
            "N": 100,
            "S_t": 1.15,  # EUR/USD
            "r": 0.025,  # USD rate
            "K": 1.20,
            "q": None,
            "r_f": 0.015,  # EUR rate
            "asset_type": "currency",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "Future_european_put",
        {
            "sigma": 0.35,
            "T": 0.5,
            "N": 100,
            "S_t": 2200.0,
            "r": 0.02,
            "K": 2300.0,
            "q": None,
            "r_f": None,
            "asset_type": "future",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "Deep_ITM_european_put",
        {
            "sigma": 0.30,
            "T": 1.5,
            "N": 250,
            "S_t": 80.0,
            "r": 0.03,
            "K": 120.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "High_dividend_european_put",
        {
            "sigma": 0.25,
            "T": 1.0,
            "N": 200,
            "S_t": 100.0,
            "r": 0.04,
            "K": 100.0,
            "q": 0.08,
            "r_f": None,
            "asset_type": "dividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "Short_term_european_put",
        {
            "sigma": 0.40,
            "T": 1.0 / 12.0,  # 1 month
            "N": 30,
            "S_t": 100.0,
            "r": 0.02,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "Very_low_vol_european_put",
        {
            "sigma": 0.05,
            "T": 1.0,
            "N": 150,
            "S_t": 95.0,
            "r": 0.03,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "Long_term_OTM_european_put",
        {
            "sigma": 0.20,
            "T": 3.0,
            "N": 500,
            "S_t": 120.0,
            "r": 0.04,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
]

# Edge cases for robustness testing - European only
EUROPEAN_EDGE_CASES: List[Tuple[str, dict]] = [
    (
        "Min_time_steps_european",
        {
            "sigma": 0.20,
            "T": 0.25,
            "N": 1,  # Minimum steps
            "S_t": 100.0,
            "r": 0.05,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Very_short_expiry_european",
        {
            "sigma": 0.20,
            "T": 1.0 / 365.0,  # 1 day
            "N": 10,
            "S_t": 100.0,
            "r": 0.05,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "put",
        },
    ),
    (
        "High_time_steps_european",
        {
            "sigma": 0.25,
            "T": 1.0,
            "N": 1000,  # Many steps for convergence testing
            "S_t": 100.0,
            "r": 0.03,
            "K": 105.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Zero_interest_rate_european",
        {
            "sigma": 0.30,
            "T": 1.0,
            "N": 100,
            "S_t": 100.0,
            "r": 0.0,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
    (
        "Very_high_volatility_european",
        {
            "sigma": 2.0,  # 200% vol
            "T": 1.0,
            "N": 200,
            "S_t": 100.0,
            "r": 0.05,
            "K": 100.0,
            "q": None,
            "r_f": None,
            "asset_type": "nondividend",
            "exercise_type": "european",
            "option_type": "call",
        },
    ),
]
